[package]
name = "kissg"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.8.2"
async-channel = "2.3.1"
regex = "1.10.5"

[dependencies.adw]
package = "libadwaita"
version = "0.6.0"
features = ["v1_2"]
